FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# OS deps for mysqlclient, etc.
RUN apt-get update && apt-get install -y --no-install-recommends \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    curl \
    netcat-traditional \
    libpoppler-cpp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy app (must include requirements.txt inside backend_app/)
COPY backend_app/ ./

# Install Python deps
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# If your Flask app exposes 'app = Flask(__name__)' in app.py, this is robust:
# We use gunicorn instead of flask since it allows us to set the "--timeout" flag (stops flask timeouts for lengthy processes like upload_file) and "workers"
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "900", "--workers", "3", "app:app"]
